# Namų darbai 7. Pandas

In [ ]:
# 1. Sukurkite naują DataFrame naudodami žodyną sales.
# Panagrinėkite kaip šis žodynas sukurtas, ar suprantate kokie objektai yra žodyno reikšmės?
# sales = {'day': list(range(1,31)), 'sales': (np.random.rand(30)*1000).round(2)}

In [23]:
import numpy as np
import pandas as pd
sales = {'day': list(range(1,31)), 'sales': (np.random.rand(30)*1000).round(2)}
# print(sales)
print(type(sales['day']))
print(type(sales['sales']))
print(sales['sales'].shape)

<class 'list'>
<class 'numpy.ndarray'>
(30,)

In [5]:
df = pd.DataFrame(sales)
df

    day   sales
0     1  379.57
1     2  436.25
2     3  148.38
3     4  673.17
4     5  356.20
5     6  364.11
6     7   75.62
7     8   74.84
8     9  525.33
9    10  449.54
10   11  318.43
11   12   19.90
12   13  523.92
13   14  634.69
14   15   40.17
15   16  436.99
16   17  811.82
17   18  879.15
18   19  738.94
19   20  718.50
20   21  382.61
21   22  612.39
22   23  272.32
23   24  303.13
24   25  158.84
25   26  942.00
26   27  597.62
27   28  406.24
28   29  278.79
29   30  791.61

In [ ]:
# 2. Sukurkite dataframe fruits, kuris atrodo šitaip:
#        Apples Bananas
#   0       30       21

In [27]:
dict = {
    'Apples': [30], 'Bananas': [21]
}

fruits = pd.DataFrame(dict)
fruits

   Apples  Bananas
0      30       21

In [ ]:
# 3. Sukurkite dataframe fruit_sales, kuris atrodo šitaip:
#              Apples Bananas
#   2017 Sales     35      21
#   2018 Sales     41      34

In [28]:
fruit_sales = pd.DataFrame({'Apples': [35,41], 'Bananas':[21,34]}, index = ['2017 Sales', '2018 Sales'])
fruit_sales

            Apples  Bananas
2017 Sales      35       21
2018 Sales      41       34

In [ ]:
# 4. Sukurkite Series ingredients, kuris atrodo šitaip:
#   Flour     4 cups
#   Milk       1 cup
#   Eggs     2 large
#   Spam       1 can
#   Name: Dinner, dtype: object

In [38]:
df = pd.DataFrame({'Name': ['Flour', 'Milk', 'Eggs','Spam'], 'Dinner': ['4 cups', '1 cup', '2 large', '1 can']}).set_index('Name')

        Dinner
Name
Flour   4 cups
Milk     1 cup
Eggs   2 large
Spam     1 can

In [43]:
ingredients = df['Dinner']
print(ingredients)

type(ingredients)

Name
Flour     4 cups
Milk       1 cup
Eggs     2 large
Spam       1 can
Name: Dinner, dtype: object

pandas.core.series.Series

In [ ]:
#5. Sukurkite DataFrame pavadinimu reviews nuskaitydami csv failą winemag-data.csv (failas pridėtas prie 7 paskaitos)
# nurodykite 'pandas' naudoti pirmąjį failo stulpelį indeksui

In [47]:
reviews = pd.read_csv('winemag-data.csv', index_col=0)
reviews.head(2)

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos

In [ ]:
# 6. Iš failo winemag-data.csv atspausdinkite reviews stulpelį 'description'
# keturiais skirtingais būdais ([], ., iloc, loc)

In [54]:
print(reviews['description'])

0         Aromas include tropical fruit, broom, brimston...
1         This is ripe and fruity, a wine that is smooth...
2         Tart and snappy, the flavors of lime flesh and...
3         Pineapple rind, lemon pith and orange blossom ...
4         Much like the regular bottling from 2012, this...
                                ...
129966    Notes of honeysuckle and cantaloupe sweeten th...
129967    Citation is given as much as a decade of bottl...
129968    Well-drained gravel soil gives this wine its c...
129969    A dry style of Pinot Gris, this is crisp with ...
129970    Big, rich and off-dry, this is powered by inte...
Name: description, Length: 129971, dtype: object

In [55]:
print(reviews.description)

0         Aromas include tropical fruit, broom, brimston...
1         This is ripe and fruity, a wine that is smooth...
2         Tart and snappy, the flavors of lime flesh and...
3         Pineapple rind, lemon pith and orange blossom ...
4         Much like the regular bottling from 2012, this...
                                ...
129966    Notes of honeysuckle and cantaloupe sweeten th...
129967    Citation is given as much as a decade of bottl...
129968    Well-drained gravel soil gives this wine its c...
129969    A dry style of Pinot Gris, this is crisp with ...
129970    Big, rich and off-dry, this is powered by inte...
Name: description, Length: 129971, dtype: object

In [56]:
print(reviews.iloc[:,1])

0         Aromas include tropical fruit, broom, brimston...
1         This is ripe and fruity, a wine that is smooth...
2         Tart and snappy, the flavors of lime flesh and...
3         Pineapple rind, lemon pith and orange blossom ...
4         Much like the regular bottling from 2012, this...
                                ...
129966    Notes of honeysuckle and cantaloupe sweeten th...
129967    Citation is given as much as a decade of bottl...
129968    Well-drained gravel soil gives this wine its c...
129969    A dry style of Pinot Gris, this is crisp with ...
129970    Big, rich and off-dry, this is powered by inte...
Name: description, Length: 129971, dtype: object

In [65]:
reviews.loc[:,'description']

0         Aromas include tropical fruit, broom, brimston...
1         This is ripe and fruity, a wine that is smooth...
2         Tart and snappy, the flavors of lime flesh and...
3         Pineapple rind, lemon pith and orange blossom ...
4         Much like the regular bottling from 2012, this...
                                ...
129966    Notes of honeysuckle and cantaloupe sweeten th...
129967    Citation is given as much as a decade of bottl...
129968    Well-drained gravel soil gives this wine its c...
129969    A dry style of Pinot Gris, this is crisp with ...
129970    Big, rich and off-dry, this is powered by inte...
Name: description, Length: 129971, dtype: object

In [ ]:
# 7. Iš failo winemag-data.csv atspausdinkite pirmąją 'description' stulpelio reikšmę visais būdais kiek išeina sugalvot

In [75]:
    print(reviews['description'][0])
    print(reviews.description[0])
    print(reviews.iloc[0,1])
    print(reviews.loc[0,'description'])

Aromas include tropical fruit, broom, brimstone and dried herb. The palate isn't overly expressive, offering unripened apple, citrus and dried sage alongside brisk acidity.
Aromas include tropical fruit, broom, brimstone and dried herb. The palate isn't overly expressive, offering unripened apple, citrus and dried sage alongside brisk acidity.
Aromas include tropical fruit, broom, brimstone and dried herb. The palate isn't overly expressive, offering unripened apple, citrus and dried sage alongside brisk acidity.
Aromas include tropical fruit, broom, brimstone and dried herb. The palate isn't overly expressive, offering unripened apple, citrus and dried sage alongside brisk acidity.

In [ ]:
# 8. Iš failo winemag-data.csv atspausdinkite tik pirmąją reviews eilutę

In [77]:
reviews.head(1)

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia

In [ ]:
# 10. Iš failo winemag-data.csv atspausdinkite pirmųjų 10 vynų pavadinimus (title)

In [78]:
reviews['title'].head(10)

0                    Nicosia 2013 Vulkà Bianco  (Etna)
1        Quinta dos Avidagos 2011 Avidagos Red (Douro)
2        Rainstorm 2013 Pinot Gris (Willamette Valley)
3    St. Julian 2013 Reserve Late Harvest Riesling ...
4    Sweet Cheeks 2012 Vintner's Reserve Wild Child...
5    Tandem 2011 Ars In Vitro Tempranillo-Merlot (N...
6     Terre di Giurfo 2013 Belsito Frappato (Vittoria)
7                Trimbach 2012 Gewurztraminer (Alsace)
8    Heinz Eifel 2013 Shine Gewürztraminer (Rheinhe...
9    Jean-Baptiste Adam 2012 Les Natures Pinot Gris...
Name: title, dtype: object

In [ ]:
# 11. Iš failo winemag-data.csv atspausdinkite eilutes su indeksais 1, 2, 3, 5, 8

In [79]:
reviews.loc[[1,2,3,5,8]]

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
5,Spain,Blackberry and raspberry aromas show a typical...,Ars In Vitro,87,15.0,Northern Spain,Navarra,NaN,Michael Schachner,@wineschach,Tandem 2011 Ars In Vitro Tempranillo-Merlot (N...,Tempranillo-Merlot,Tandem
8,Germany,Savory dried thyme notes accent sunnier flavor...,Shine,87,12.0,Rheinhessen,NaN,NaN,Anna Lee C. Iijima,NaN,Heinz Eifel 2013 Shine Gewürztraminer (Rheinhe...,Gewürztraminer,Heinz Eifel

In [ ]:
# 12. Iš failo winemag-data.csv atspausdinkite DataFrame su stulpeliais
# country, province, region_1 ir region_2 ir eilutėmis, kurių indeksai yra 0, 1, 10 ir 100

In [81]:
reviews.loc[[0,1,10,100], ['country', 'province', 'region_1', 'region_2']]

      country           province      region_1      region_2
0       Italy  Sicily & Sardinia          Etna           NaN
1    Portugal              Douro           NaN           NaN
10         US         California   Napa Valley          Napa
100        US           New York  Finger Lakes  Finger Lakes

In [ ]:
# 13. Iš winemag-data.csv failo atspausdinkite visas eilutes, kur šalis yra Ispanija (Spain)

In [82]:
reviews[reviews['country'] == 'Spain']

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
5,Spain,Blackberry and raspberry aromas show a typical...,Ars In Vitro,87,15.0,Northern Spain,Navarra,NaN,Michael Schachner,@wineschach,Tandem 2011 Ars In Vitro Tempranillo-Merlot (N...,Tempranillo-Merlot,Tandem
18,Spain,"Desiccated blackberry, leather, charred wood a...",Vendimia Seleccionada Finca Valdelayegua Singl...,87,28.0,Northern Spain,Ribera del Duero,NaN,Michael Schachner,@wineschach,Pradorey 2010 Vendimia Seleccionada Finca Vald...,Tempranillo Blend,Pradorey
81,Spain,"Bland, mature aromas of white fruits are on th...",NaN,86,16.0,Galicia,Rías Baixas,NaN,Michael Schachner,@wineschach,Spyro 2014 Albariño (Rías Baixas),Albariño,Spyro
154,Spain,"Ripe aromas of raisin, black plum and horsehid...",Single Vineyard Estate Bottled,91,50.0,Central Spain,Dominio de Valdepusa,NaN,Michael Schachner,@wineschach,Marques de Griñon 2010 Single Vineyard Estate ...,Graciano,Marques de Griñon
212,Spain,Mellow white-fruit aromas are nonspecific and ...,Fermentado en Barrica,90,40.0,Northern Spain,Rueda,NaN,Michael Schachner,@wineschach,Matarromera 2015 Fermentado en Barrica Verdejo...,Verdejo,Matarromera
...,...,...,...,...,...,...,...,...,...,...,...,...,...
129884,Spain,"After 23 months in barrel, this Viura-Malvasia...",Gran Reserva,91,43.0,Northern Spain,Rioja,NaN,Michael Schachner,@wineschach,Valserrano 2009 Gran Reserva White (Rioja),White Blend,Valserrano
129902,Spain,Dry apple and lemon aromas are clean and one s...,Finca Las Marcas Fermentado en Barrica,91,40.0,Northern Spain,Rueda,NaN,Michael Schachner,@wineschach,Carlos Moro 2015 Finca Las Marcas Fermentado e...,Verdejo,Carlos Moro
129928,Spain,This represents Torres' highest effort in Prio...,Salmos Perpetual,91,52.0,Catalonia,Priorat,NaN,Michael Schachner,@wineschach,Torres 2005 Salmos Perpetual Red (Priorat),Red Blend,Torres
129930,Spain,"Arguably on the heavy and rich side, but if yo...",Crianza,91,26.0,Northern Spain,Ribera del Duero,NaN,Michael Schachner,@wineschach,Costaval 2005 Crianza (Ribera del Duero),Tempranillo Blend,Costaval
129957,Spain,Lightly baked berry aromas vie for attention w...,Crianza,90,17.0,Northern Spain,Rioja,NaN,Michael Schachner,@wineschach,Viñedos Real Rubio 2010 Crianza (Rioja),Tempranillo Blend,Viñedos Real Rubio

In [ ]:
# 14. Iš winemag-data.csv failo atspausdinkite tų vynų pavadinimus ir kainas,
# kurie yra iš Australijos ('Australia') arba Naujosios Zelandijos ('New Zealand') ir kurie surinko bent 95 taškus

In [90]:
reviews[reviews['country'].isin(['Australia', 'New Zealand']) & (reviews['points'] >= 95)][['title', 'price']]

                                                    title  price
345     Chambers Rosewood Vineyards NV Rare Muscat (Ru...  350.0
346     Chambers Rosewood Vineyards NV Rare Muscadelle...  350.0
348     Chambers Rosewood Vineyards NV Grand Muscat (R...  100.0
349        Torbreck 2012 RunRig Shiraz-Viognier (Barossa)  225.0
356     Jasper Hill 2013 Georgia's Paddock Shiraz (Hea...   85.0
360     Torbreck 2012 Descendant Shiraz-Viognier (Baro...  125.0
365     Wakefield 2013 St. Andrews Single Vineyard Rel...   60.0
14354       Kaesler 2006 Old Vine Shiraz (Barossa Valley)   60.0
16538   Lambert 2013 The Family Tree Shiraz (Barossa V...   65.0
28573     Clarendon Hills 2005 Astralis Syrah (Clarendon)  350.0
34502     Standish 2006 The Relic Shiraz (Barossa Valley)  135.0
34506   Standish 2005 The Standish Single Vineyard Shi...  135.0
38988   Penfolds 2009 Bin 707 Cabernet Sauvignon (Sout...  200.0
39059   Wakefield 2013 St. Andrews Single Vineyard Rel...   60.0
39961       Penfolds 1996 Grange Shiraz (South Australia)  185.0
39962           Penfolds 1998 RWT Shiraz (Barossa Valley)   70.0
45809     Clarendon Hills 2007 Astralis Syrah (Clarendon)  225.0
56953       Penfolds 2010 Grange Shiraz (South Australia)  850.0
56956    Standish 2012 Andelmonde Shiraz (Barossa Valley)   95.0
56957   Thorn Clarke 2012 Ron Thorn Single Vineyard Sh...   89.0
56959    Henschke 2010 Hill of Grace Shiraz (Eden Valley)  820.0
59977   Hickinbotham 2013 The Peake Cabernet-Shiraz (M...  150.0
59984            Heartland 2013 One Red (Langhorne Creek)   95.0
67096   R.L. Buller & Son NV Calliope Rare Tokay (Ruth...   86.0
67101   Chambers Rosewood Vineyards NV Rare Muscat (Ru...  300.0
76392   Jasper Hill 2012 Georgia's Paddock Shiraz (Hea...   85.0
77028       Penfolds 2008 Grange Shiraz (South Australia)  850.0
77036           Penfolds 2009 RWT Shiraz (Barossa Valley)  150.0
77037   Torbreck 2007 RunRig Shiraz-Viognier (Barossa ...  225.0
77042        John Duval Wines 2010 Eligo Shiraz (Barossa)  100.0
77044   Kilikanoon 2009 R Reserve Shiraz (Barossa Valley)  105.0
77046    Torbreck 2007 The Factor Shiraz (Barossa Valley)  125.0
83357       Penfolds 2004 Grange Shiraz (South Australia)  500.0
84815           Torbreck 2012 The Factor Shiraz (Barossa)  125.0
84816          Nashwauk 2010 Beacon Shiraz (McLaren Vale)  145.0
87128   Kay Brothers 2012 Amery Vineyard Block 6 Shira...  120.0
87137   Moss Wood 2011 Cabernet Sauvignon (Margaret Ri...   84.0
87143   Wakefield 2012 St. Andrews Single Vineyard Rel...   60.0
91851        Trinity Hill 2013 Homage Syrah (Hawke's Bay)  100.0
98386   D'Arenberg 2010 Little Venice Single Vineyard ...   85.0
99318   Henschke 2014 Mount Edelstone Vineyard Shiraz ...  200.0
99330   Penfolds 2014 Bin 707 Cabernet Sauvignon (Sout...  500.0
99340    Torbreck 2013 Les Amis Grenache (Barossa Valley)  185.0
109427  Chambers Rosewood Vineyards NV Rare Muscadelle...  300.0
109434  D'Arenberg 2010 The Swinging Malaysian Single ...   85.0
122421  Glaetzer 2010 Amon-Ra Unfiltered Shiraz (Baros...  110.0
122430  Glaetzer 2010 Anaperenna Shiraz-Cabernet Sauvi...   80.0
122507  Squawking Magpie 2014 SQM Gimblett Gravels Cab...   79.0
122939   Torbreck 2013 The Factor Shiraz (Barossa Valley)  125.0

In [ ]:
# 15. winemag-data.csv faile sukurkite naują stulpelį price_gbp,
# kuriame būtų vyno kaina svarais sterlingais (laikykite, kad $1 = £0.73)

In [92]:
reviews['price_gbp'] = reviews['price'] * 0.79
reviews.head(2)

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery,price_gbp
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia,NaN
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos,11.85

In [ ]:
# 16. Kokia yra vidutinė portugališkų vynų kaina svarais winemag-data.csv faile?

In [98]:
reviews[reviews['country'] == 'Portugal']['price'].mean()

26.21825641025641

In [ ]:
# 17. Kiek skirtingų vyno (ar vynuogių) rūšių 'variety' yra winemag-data.csv lentelėje?

In [105]:
reviews['variety'].drop_duplicates()

0                      White Blend
1                   Portuguese Red
2                       Pinot Gris
3                         Riesling
4                       Pinot Noir
                    ...
126782                     Pignolo
127085                  Caprettone
127521                      Ondenc
127959                      Athiri
129187    Bobal-Cabernet Sauvignon
Name: variety, Length: 708, dtype: object

In [109]:
len(reviews['variety'].unique())

708

In [ ]:
# 18. Kiek kokios rūšies vynų yra winemag-data.csv duomenų rinkinyje?

In [107]:
reviews['variety'].value_counts()

Pinot Noir                  13272
Chardonnay                  11753
Cabernet Sauvignon           9472
Red Blend                    8946
Bordeaux-style Red Blend     6915
                            ...
Bombino Nero                    1
Barbera-Nebbiolo                1
Franconia                       1
Bobal-Cabernet Sauvignon        1
Blauburgunder                   1
Name: variety, Length: 707, dtype: int64

In [ ]:
# 19. Kokia vyno rūšis populiariausia winemag-data.csv duomenų rinkinyje?
# (naudokite Series metodą .idxmax(), kuris grąžina didžiausios Series vertės indeksą)

In [118]:
reviews['variety'].value_counts().idxmax()

'Pinot Noir'

In [ ]:
# 20. Sukurkite funkciją is_tropical() winemag-data.csv duomenų rinkinyje,
# kuri priima string kintamąjį ir grąžina ar jame yra žodis 'tropical' (True/False)

In [148]:
def is_tropical(text):
    x = False
    if 'tropical' in text.lower():
        x = True
    else:
        x = False
    return x

In [ ]:
# 21. Naudodami .map() metodą ir nežymiai modifikuotą ką tik sukurtą funkciją,
# suskaičiuokite kiek vynų aprašymų (description) naudoja žodį 'tropical'

In [153]:
reviews['is_tropical'] = reviews['description'].map(is_tropical)

In [154]:
reviews.head()

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery,price_gbp,is_tropical
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia,NaN,True
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos,11.85,False
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm,11.06,False
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian,10.27,False
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks,51.35,False

In [156]:
reviews['is_tropical'].value_counts()

False    126171
True       3800
Name: is_tropical, dtype: int64